---
title: "Project Proposal"
author: Yifei Qu, Boxiong Du
format: html
editor: visual
---

## Dataset 1

The first dataset we selected is the Steam games dataset. It was created 6 months ago by scraping data through the Steam webAPI. The data has 39 variables, which can be split into two genres: game information and game play. Game information contains variables such as game name, developer, game price, review, and game genre etc,. Game play contains variables such as peak concurrent users(CCU) and median playtime of players(both overall and in the past two weeks).

We find the Steam dataset especially compelling because it brings together both engagement metrics—like CCU and median play time—and commercial factors such as price, along with user-generated content in the form of reviews. We are very interested in the game industry and would really like to use data to provide insights to the performance of games.

We would like to ask the question: How is median gameplay time affected by other variables?

Our goal is to build a machine learning model to predict peak concurrent users. We expect to perform some data cleaning including dropping duplicates, drop null values, and some feature engineering. Then we plan to build a linear regression model if the variables are in a linear relationship. Generally we would predict lower price game with high positive reviews and long median playtime to have higher CCU.

## Dataset 2

The second dataset we selected is the California Housing Prices dataset. This dataset was originally collected from the 1990 US Census and contains information about housing districts in California. It includes 20,640 observations and 10 variables, including house value, income, house characteristics, locations, and so on.

We are interested in studying this dataset because it provides a comprehensive view of housing prices in California, a state known for its diverse real estate market. There are a large number of factors that can affect the value of a house property, and the housing market itself is quite a volatile industry, and is quite dependent on demand and supply fluctuations, so it's really hard to predict the price variation over time. Using this dataset, we plan to explore the factors that influence housing prices and build a predictive model to estimate the median house value based on features like median income, location, and housing characteristics. Specifically, we propose the following research question: What are the key factors influencing housing prices in California, and how accurately can we predict median house values using these factors?

Specifically, we would conduct exploratory data analysis first to see the trends of the data and deal with outliers and missing values. Then we plan to use linear regression model to predict median house values and assess the model's accuracy and liability through MSE and R-sqaured.
